"""Added Subscription

Revision ID: 5f4e61f676f8
Revises: eb89f5587edf
Create Date: 2025-11-07 19:01:20.177816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4e61f676f8'
down_revision: Union[str, Sequence[str], None] = 'eb89f5587edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subscription_metadata', sa.Text(), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_subscriptions_current_period_end'), 'stripe_subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_stripe_customer_id'), 'stripe_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), 'stripe_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_stripe_subscriptions_user_id'), 'stripe_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_subscriptions_user_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_customer_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_current_period_end'), table_name='stripe_subscriptions')
    op.drop_table('stripe_subscriptions')
    # ### end Alembic commands ###
