"""Added task counts

Revision ID: d2b79dc1785e
Revises: bc3e17126050
Create Date: 2025-11-09 19:48:19.446197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b79dc1785e'
down_revision: Union[str, Sequence[str], None] = 'bc3e17126050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_reports', sa.Column('completed_tasks', sa.Integer(), nullable=False))
    op.add_column('monthly_reports', sa.Column('missed_tasks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_reports', 'missed_tasks')
    op.drop_column('monthly_reports', 'completed_tasks')
    # ### end Alembic commands ###
